services:
  postgres:
    image: postgres:16
    container_name: ditto_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ditto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ditto_network

  adminer:
    image: adminer
    container_name: ditto_adminer
    ports:
      - "8080:8080"
    networks:
      - ditto_network

volumes:
  postgres_data:

networks:
  ditto_network:
    driver: bridge
